- name: "manage worker 1"
  hosts: "web"
  become: true
  tasks:
    - name: "install maven"
      become: yes
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
           - maven


 
