- name: "manage worker 1"
  hosts: "web"
  become: true
  tasks:
   - name: "install maven"
     apt:
        pkg: "{{ item }}"
          state: present
          update_cache: yes
          cache_valid_time: 3600
            with_items:
              - maven
              - apache2

 
