- name: "manage worker 1"
  hosts: web
  become: true
  tasks:
  - name: "clone addressbook repository"
    ansible.builtin.git:
     repo: https://github.com/marysh995/addressbook.git
     dest: /labsuser/CEB
     clone: yes
     update: yes
     
  - name: "install maven"
    apt:
      name: maven
      state: present
      
  - name: "change the dir and package"
    command: mvn package
    args:
      chdir: /labsuser/CEB

  - name: "install JDK 11"
    apt:
      name: openjdk-11-jdk
      state: present

  - name: "add tomcat group"
    group:
      name: tomcat

  - name: "add tomcat user"
    user:
      name: tomcat
      group: tomcat
      home: /user/share/tomcat
      createhome: no

  - name: "create /opt/tomcat directory"
    file:
      path: /opt/tomcat
      state: directory
      mode: 0755

  - name: "download & unarchive"
    unarchive:
      src: http://apache.cs.utah.edu/tomcat/tomcat-9/v9.0.71/bin/apache-tomcat-9.0.71.tar.gz
      dest: /opt/tomcat
      remote_src: yes
      extra_opts: [--strip-components=1]

  - name: "Change ownership"
    file:
      path: /opt/tomcat
      owner: tomcat
      group: tomcat
      mode: "u+rwx,g+rx,o=rx"
      recurse: yes
      state: directory

  - name: "Start and enable Tomcat service"
    systemd:
      name: tomcat
      state: started
      enabled: true
      daemon_reload: true
    
  
          
              

 
