- name: "manage worker 1"
  hosts: "web"
  become: true
  tasks:
    - name: "install maven"
      become: true
      apt:
        name: "maven"
        state: present
        update_cache: yes
      vars:
        packages:
           - maven


 
