- name: "manage worker 1"
  hosts: web
  become: true
  vars:
      tomcat_ver: 9.0.64
      ui_manager_user: admin
      ui_manager_pass: Str0ngManagerP@ssw3rd
      ui_admin_username: admin
      ui_admin_pass: Str0ngAdminP@ssw3rd
  tasks:
  - name: "clone addressbook repository"
    ansible.builtin.git:
     repo: https://github.com/marysh995/addressbook.git
     dest: /labsuser/CEB
     clone: yes
     update: yes
     
  - name: "install maven"
    apt:
      name: maven
      state: present
      
  - name: "change the dir and package"
    command: mvn package
    args:
      chdir: /labsuser/CEB 
  
  - name: "install tomcat9"
    roles:
      - tomcat

    
  
          
              

 
