- name: "manage worker 1"
  hosts: "web"
  become: true
  tasks:
    - name: "maven build"
      become: true
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
           - maven
