- name: "manage worker 1"
  hosts: "web"
  become: true
  tasks:
    - name: "install maven"
      become: true
      apt:
        packageType: 'maven' 
        state: latest 
        update_cache: yes 
        cache_valid_time: 3600
      

 
