- name: "manage worker 1"
  hosts: "web"
  become: true
  tasks:
    - name: "install maven"
      become: true
      apt: 
            pkg: 
            with_items:
              - "{{ foo }}"
            state: latest 
            update_cache: yes 
            cache_valid_time: 3600
      with_items:
        - maven
