- name: "manage worker 1"
  hosts: web
  become: true
  tasks:
  - name: "clone addressbook repository"
    ansible.builtin.git:
     repo: https://github.com/marysh995/addressbook.git
     dest: /labsuser/CEB
     clone: yes
     update: yes
     
  - name: "install maven"
    apt:
      name: maven
      state: present
      
  - name: "change the dir and package"
    command: mvn package
    args:
      chdir: /labsuser/CEB 
   
   
    
  
          
              

 
