- name: "manage worker 1"
  hosts: "web"
  become: true
  tasks:
    apt:
      - name: "maven"
        state: present
        update_cache: yes
   - name: "clone addressbook repository"
     repo: https://github.com/marysh995/addressbook.git
     
          
              

 
